config/routes.rb
NeaMap::Application.routes.draw do
  resources :grantees
  resources :venues
  root :to => 'home#index'

end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
  attr_accessible :name
  has_many :venues
end

app/models/grantee.rb
class Grantee < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :fiscal_year, :grant_num, :grantee_name, :latitude, 
                  :longitude, :nea_office_id, :state, :url, :zip, :nea_office
  belongs_to :nea_office

  reverse_geocoded_by :latitude, :longitude

end

app/models/nea_office.rb
class NeaOffice < ActiveRecord::Base
  attr_accessible :name
  has_many :grantees
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :activity_type_id, :address1, :address2, :city, :event_year, 
                  :facility_type_id, :grant_num, :grantee, :latitude, :longitude, 
                  :name, :nea_venue_id, :state, :venue_type_id, :zip, :activity_type, :venue_type
  belongs_to :activity_type
  belongs_to :venue_type

  reverse_geocoded_by :latitude, :longitude

end

app/models/venue_type.rb
class VenueType < ActiveRecord::Base
  attr_accessible :name
  has_many :venues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/grantees_controller.rb
class GranteesController < ApplicationController
  def index
    @grantees = Grantee.near("#{params[:zip]}",100)
    Rails.logger.debug("\n\n**** grantees: #{@grantees.count}")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :json
  def index
    @grantees = Grantee.near([27.98152,-82.44591],20)
    @venues = Venue.near([27.98152,-82.44591],20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def safe_url(url, link_text = nil, show_text_if_no_link = false)
    if !url.blank?
      if url[0..4] != 'http:'
           url = 'http://' + url
      end
      link_text = url unless !link_text.blank?
      return link_to(link_text, url)
    else
      show_text_if_no_link ? result = link_text : result = nil
      return result
    end
  end
end

app/helpers/grantees_helper.rb
module GranteesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/grantees/index.html.haml
%table
  %thead
    %tr
      %th Grantee
      %th Fiscal Year
      %th NEA Office
      %th Venue
  - @grantees.each do |grantee|

    %tr
      %td= safe_url grantee.url, grantee.grantee_name, grantee.grantee_name
      %td= grantee.fiscal_year
      %td= grantee.nea_office.name
      %td

app/views/home/index.html.haml
.row
  %h1 NEA Grantee Map
.row
  .large-12.columns
    .row  
      .large-2.columns
        = form_tag grantees_path, :method => :get, 'data-update-target' => 'grantees_list', remote: true do |form|
          = label_tag :zip, 'Find Grantees near...'
          = text_field_tag :zip, '', :placeholder => '33606'
          = submit_tag 'Go'

.row
  .large-12.columns
    #grantees_list

  .large-12.columns
    .row
      #map{:style=>"width:800px; height:300px;"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "NEA Grantee Map" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <script src="http://open.mapquestapi.com/sdk/js/v7.0.s/mqa.toolkit.js?key=Fmjtd%7Cluub2g62nl%2Cr2%3Do5-9uan5f"></script> 

    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>